apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: handsome-mammal-nodejs 
  janus-idp.io/tekton: handsome-mammal-nodejs
  backstage.io/kubernetes-id: handsome-mammal-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: handsome-mammal-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  